import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@mantine/core/styles.css'
import '@/app/globals.scss'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import Head from 'next/head'
import ProgressBar from '@/components/sections/progressbar'
import { Suspense } from 'react'
import { YMInitializer } from 'react-yandex-metrika'

export const metadata: Metadata = {
	title: 'SGM Motors',
	description: 'Generated by create next app'
}

const montserrat = Montserrat({
	subsets: ['latin']
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<Head>
				<ColorSchemeScript />
			</Head>
			<body className={`${montserrat.className} antialiased bg-gray-100`}>
				<Suspense>
					<YMInitializer accounts={[100870448]} />
					<ProgressBar />
				</Suspense>
				<MantineProvider>
					<div className='bg-gray-200 min-h-20 md:min-h-[130px]'></div>
					{children}
					<Notifications className='fixed top-[20px] right-[10px] z-50' />
				</MantineProvider>
			</body>
		</html>
	)
}
