import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@mantine/core/styles.css'
import '@/app/globals.scss'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import Head from 'next/head'
import ProgressBar from '@/components/sections/progressbar'
import { Suspense } from 'react'
import Script from 'next/script'
import YandexMetrika from '@/components/layout/YandexMetrika'

export const metadata: Metadata = {
	title: 'SGM Motors',
	description: 'Generated by create next app'
}

const montserrat = Montserrat({
	subsets: ['latin']
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<Head>
				<ColorSchemeScript />
			</Head>
			<body className={`${montserrat.className} antialiased bg-gray-100`}>
				<Script id='metrika-counter' strategy='afterInteractive'>
					{`(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
					m[i].l=1*new Date();
					for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
					k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
					(window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
				
					ym(100870448, "init", {
						defer: true,
						clickmap:true,
						trackLinks:true,
						accurateTrackBounce:true,
						webvisor:true
					});`}
				</Script>
				<Suspense fallback={<></>}>
					<YandexMetrika />
				</Suspense>
				<Suspense>
					<ProgressBar />
				</Suspense>
				<MantineProvider>
					<div className='bg-gray-200 min-h-20 md:min-h-[130px]'></div>
					{children}
					<Notifications className='fixed top-[20px] right-[10px] z-50' />
				</MantineProvider>
			</body>
		</html>
	)
}
